// import ApexUtils from 'c/apexUtils';

describe("c-apex-utils", () => {
  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange

    // Act

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
